package com.typestrike.ui.gameplay

import kotlin.random.Random

/**
 * Local word bank for generating words per level.
 * The backend doesn't serve gameplay words, so we generate them locally
 * based on the level's word length range and word count.
 */
object WordBank {

    // ── Common English Words ────────────────────────────
    // Declared BEFORE WORDS_BY_LENGTH to ensure proper initialization order.
    // Split into parts by word length to avoid 64KB method bytecode limit on Android.

    private val WORDS_3 = listOf(
        "the", "and", "for", "are", "but", "not", "you", "all", "can", "had",
        "her", "was", "one", "our", "out", "has", "get", "him", "his", "how",
        "its", "may", "new", "now", "old", "see", "she", "two", "use", "way",
        "who", "yes", "act", "add", "age", "ago", "air", "arm", "art", "ask",
        "bad", "bag", "bar", "bed", "big", "bit", "box", "boy", "bus", "but",
        "buy", "cap", "car", "cat", "cup", "cut", "day", "did", "dig", "dog",
        "dot", "dry", "ear", "eat", "egg", "end", "eye", "fan", "far", "fat",
        "few", "fit", "fix", "fly", "fun", "gap", "gas", "god", "got", "gun",
        "gut", "guy", "hat", "hit", "hot", "ice", "ill", "job", "joy", "key",
        "kid", "kit", "lab", "lap", "law", "lay", "leg", "let", "lid", "lip",
        "log", "lot", "low", "mad", "map", "mix", "net", "nor", "odd", "off",
        "oil", "owe", "own", "pad", "pan", "pay", "pen", "pet", "pie", "pin",
        "pit", "pop", "pot", "put", "raw", "red", "row", "rub", "run", "sad",
        "sat", "say", "set", "six", "ski", "son", "sum", "sun", "tap", "tax",
        "tea", "ten", "the", "tie", "tin", "tip", "toe", "ton", "too", "top",
        "toy", "try", "two", "use", "van", "war", "wax", "web", "wet", "win",
        "won", "yes", "yet", "zoo"
    )

    private val WORDS_4 = listOf(
        "able", "also", "area", "army", "away", "back", "ball", "band", "bank",
        "bare", "barn", "base", "bath", "beak", "bear", "beat", "been", "bell",
        "belt", "bend", "bike", "bill", "bind", "bird", "bite", "bled", "blew",
        "blow", "blue", "blur", "boil", "bold", "bolt", "bond", "bone", "book",
        "boom", "boot", "bore", "born", "boss", "both", "bout", "bowl", "burn",
        "bury", "bush", "busy", "cage", "cake", "cale", "call", "calm", "came",
        "camp", "cape", "card", "care", "cart", "case", "cash", "cast", "cave",
        "cell", "chat", "chef", "chip", "chop", "cite", "city", "clad", "clam",
        "clan", "clap", "claw", "clay", "clip", "club", "clue", "coal", "coat",
        "code", "cold", "colt", "comb", "come", "cook", "cool", "cope", "copy",
        "cord", "core", "cork", "corn", "cost", "cosy", "coup", "cove", "cozy",
        "crab", "crew", "crop", "crow", "cube", "cult", "curb", "cure", "curl",
        "cute", "dame", "damp", "dare", "dark", "dash", "data", "date", "dawn",
        "dead", "deaf", "deal", "dear", "debt", "deck", "deep", "deer", "demo",
        "deny", "desk", "dial", "dice", "diet", "dirt", "disc", "dish", "disk",
        "dock", "does", "dome", "done", "doom", "door", "dose", "down", "doze",
        "drab", "drag", "draw", "drew", "drip", "drop", "drug", "drum", "dual",
        "dubs", "duck", "duel", "duke", "dull", "dumb", "dump", "dune", "dunk",
        "dusk", "dust", "duty", "dyed", "each", "earl", "earn", "ease", "East",
        "easy", "edge", "edit", "else", "emit", "envy", "even", "ever", "evil",
        "exam", "exit", "face", "fact", "fade", "fail", "fair", "fake", "fall",
        "fame", "fang", "fare", "farm", "fast", "fate", "fear", "feat", "feed",
        "feel", "fell", "fend", "fern", "fest", "file", "fill", "film", "find",
        "fine", "fire", "firm", "fish", "fist", "five", "flag", "flap", "flat",
        "flea", "fled", "flew", "flex", "flip", "flit", "float", "flock", "flood",
        "floor", "flow", "fluff", "foam", "focal", "focus", "fold", "folk", "fond",
        "font", "food", "fool", "foot", "ford", "fore", "fork", "form", "fort",
        "foul", "four", "fowl", "free", "frog", "from", "fuel", "full", "fume",
        "fund", "fuse", "fuss", "fuzz", "gain", "gale", "gall", "game", "gang",
        "gape", "garb", "gate", "gave", "gaze", "gear", "gene", "gift", "gild",
        "gill", "gilt", "gird", "girl", "gist", "give", "glad", "glee", "glen",
        "glib", "glow", "glue", "glum", "gnat", "goat", "goes", "gold", "golf",
        "gone", "good", "gore", "grab", "gram", "gray", "grew", "grid", "grim",
        "grin", "grip", "grit", "grow", "gulf", "gull", "gulp", "gunk", "gust",
        "guts", "hack", "hail", "hair", "hale", "half", "hall", "halt", "hand",
        "hang", "hard", "hare", "harm", "harp", "hash", "hate", "haul", "have",
        "haze", "hazy", "head", "heal", "heap", "hear", "heat", "heed", "heel",
        "held", "hell", "helm", "help", "herd", "here", "hero", "hide", "high",
        "hike", "hill", "hilt", "hind", "hint", "hire", "hiss", "hive", "hobo",
        "hold", "hole", "holy", "home", "hone", "hood", "hoof", "hook", "hope",
        "horn", "hose", "host", "hour", "howl", "huge", "hull", "hump", "hung",
        "hunt", "hurt", "hush", "hype", "icon", "idea", "idle", "inch", "info",
        "into", "iris", "iron", "isle", "item", "jack", "jade", "jail", "jazz",
        "jean", "jerk", "jest", "jolt", "jury", "just", "keen", "keep", "kemp",
        "kept", "kick", "kill", "kind", "king", "kiss", "kite", "knee", "knew",
        "knit", "knob", "knot", "know", "lace", "lack", "lacy", "laid", "lake",
        "lamb", "lame", "lamp", "land", "lane", "lark", "lash", "lass", "last",
        "late", "lawn", "lazy", "lead", "leaf", "leak", "lean", "leap", "left",
        "lend", "lens", "lent", "less", "liar", "lick", "lied", "life", "lift",
        "like", "limb", "lime", "limp", "line", "link", "lint", "lion", "list",
        "live", "load", "loaf", "loan", "lock", "loft", "logo", "lone", "long",
        "look", "loom", "loop", "lord", "lose", "loss", "lost", "loud", "love",
        "luck", "lull", "lump", "lung", "lure", "lurk", "lush", "lust",
        "maid", "mail", "main", "make", "male", "mall", "malt", "mane", "many",
        "mare", "mark", "mart", "mask", "mass", "mast", "mate", "maze", "mead",
        "meal", "mean", "meat", "meet", "melt", "memo", "mend", "menu", "mere",
        "mesh", "mess", "mild", "mile", "milk", "mill", "mime", "mind", "mine",
        "miss", "mist", "moan", "moat", "mock", "mode", "mold", "mole", "mood",
        "moon", "moor", "more", "moss", "most", "moth", "move", "much", "muck",
        "mule", "muse", "mush", "must", "mute", "myth", "nail", "name", "nape",
        "navy", "near", "neat", "neck", "need", "nest", "news", "next", "nice",
        "nine", "node", "none", "noon", "norm", "nose", "note", "noun", "nude",
        "numb", "oath", "obey", "odds", "omen", "omit", "once", "only", "onto",
        "ooze", "open", "oral", "orca", "oven", "over", "pace", "pack", "page",
        "paid", "pain", "pair", "pale", "palm", "pane", "pang", "park", "part",
        "pass", "past", "path", "pave", "pawn", "peak", "peal", "pear", "peat",
        "peck", "peel", "peer", "pelt", "pend", "perk", "pert", "pick", "pier",
        "pike", "pile", "pill", "pine", "pink", "pipe", "pity", "plan", "play",
        "plea", "plod", "plot", "plow", "ploy", "plug", "plum", "plus", "pock",
        "poem", "poet", "poke", "pole", "poll", "polo", "pond", "pony", "pool",
        "poor", "pope", "pork", "port", "pose", "post", "pour", "pray", "prey",
        "prow", "pull", "pulp", "pump", "punk", "pure", "push", "quit", "quiz",
        "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp",
        "rang", "rank", "rare", "rash", "rate", "rave", "read", "real", "reap",
        "rear", "reef", "reel", "rein", "rely", "rend", "rent", "rest", "rich",
        "ride", "rift", "ring", "riot", "rise", "risk", "rite", "road", "roam",
        "roar", "robe", "rock", "rode", "role", "roll", "roof", "room", "root",
        "rope", "rose", "rosy", "rout", "rude", "ruin", "rule", "rump", "run",
        "rung", "runt", "ruse", "rush", "rust", "sack", "safe", "sage", "said",
        "sail", "sake", "sale", "salt", "same", "sand", "sane", "sang", "sank",
        "save", "scab", "scan", "scat", "seal", "seam", "sear", "seat", "sect",
        "seed", "seek", "seem", "seen", "self", "sell", "send", "sent", "shed",
        "shelf", "shell", "shift", "shine", "ship", "shirt", "shock", "shoe",
        "shook", "shop", "shore", "shot", "shout", "show", "shut", "sick", "side",
        "sigh", "sign", "silk", "sill", "silt", "sing", "sink", "sire", "site",
        "size", "skid", "skim", "skin", "skip", "slab", "slag", "slam", "slap",
        "slat", "slay", "sled", "slew", "slid", "slim", "slip", "slit", "slob",
        "slop", "slot", "slow", "slug", "slum", "slur", "smog", "snap", "snip",
        "snob", "snot", "snow", "snub", "snug", "soak", "soap", "soar", "sock",
        "soda", "sofa", "soft", "soil", "sold", "sole", "some", "song", "soon",
        "soot", "sore", "sort", "soul", "sour", "span", "spar", "spec", "sped",
        "spin", "spit", "spot", "spry", "spur", "stab", "stag", "star", "stay",
        "stem", "step", "stew", "stir", "stop", "stub", "stud", "stun", "such",
        "suit", "sum", "sung", "sunk", "sure", "surf", "swan", "swap", "swim",
        "swirl", "tack", "tact", "tail", "take", "tale", "talk", "tall", "tame",
        "tank", "tape", "taps", "tart", "task", "taste", "taut", "taxi", "tbay",
        "team", "tear", "tell", "tend", "tent", "term", "test", "text", "than",
        "that", "them", "then", "they", "thin", "this", "thus", "tick", "tide",
        "tidy", "tied", "tier", "tile", "till", "tilt", "time", "tion", "tire",
        "toad", "toil", "told", "toll", "tomb", "tone", "took", "tool", "tops",
        "tore", "torn", "toss", "tour", "town", "trap", "tray", "tree", "trek",
        "trim", "trio", "trip", "trod", "trot", "true", "tube", "tuck", "tuft",
        "tuna", "tune", "turf", "turn", "tusk", "twin", "type", "ugly", "undo",
        "unit", "unto", "upon", "urge", "used", "user", "vain", "vale", "vane",
        "vary", "vast", "veil", "vein", "vent", "verb", "vest", "veto", "vice",
        "view", "vine", "void", "vote", "wade", "wage", "wail", "wait", "wake",
        "walk", "wall", "wand", "want", "ward", "warm", "warn", "warp", "wart",
        "wary", "wash", "wave", "wavy", "wax", "weak", "wean", "wear", "weed",
        "week", "weep", "weld", "well", "went", "were", "west", "what", "when",
        "whim", "whip", "whom", "wick", "wide", "wife", "wild", "will", "wilt",
        "wily", "wind", "wine", "wing", "wink", "wipe", "wire", "wise", "wish",
        "wisp", "with", "woke", "wolf", "wood", "wool", "word", "wore", "work",
        "worm", "worn", "wove", "wrap", "wren", "wrist", "yard", "year", "yell",
        "zero", "zone", "zoom"
    )

    private val WORDS_5 = listOf(
        "about", "above", "abuse", "adult", "after", "again", "agent", "agree",
        "ahead", "alarm", "album", "alien", "align", "alike", "alive", "alley",
        "allow", "alone", "along", "alter", "among", "angel", "anger", "angle",
        "ankle", "apart", "apple", "apply", "arena", "argue", "arise", "armor",
        "array", "aside", "asset", "avoid", "award", "aware", "awful", "bacon",
        "badge", "basic", "basin", "basis", "batch", "beach", "beard", "beast",
        "begin", "being", "below", "bench", "berry", "birth", "black", "blade",
        "blame", "bland", "blank", "blast", "blaze", "bleed", "blend", "bless",
        "blind", "blink", "bliss", "block", "blood", "bloom", "blown", "board",
        "boast", "bonus", "boost", "booth", "bound", "brain", "brand", "brave",
        "bread", "break", "breed", "brick", "bride", "brief", "bring", "broad",
        "broke", "brook", "brown", "brush", "buddy", "build", "built", "bunch",
        "burst", "buyer", "cabin", "cable", "candy", "carry", "catch", "cause",
        "chain", "chair", "chaos", "charm", "chart", "chase", "cheap", "check",
        "cheek", "cheer", "chess", "chest", "chief", "child", "chill", "choir",
        "chord", "chunk", "civic", "civil", "claim", "clash", "class", "clean",
        "clear", "clerk", "click", "cliff", "climb", "cling", "clock", "clone",
        "close", "cloth", "cloud", "coach", "coast", "count", "court", "cover",
        "crack", "craft", "crane", "crash", "crawl", "crazy", "cream", "crest",
        "crime", "crisp", "cross", "crowd", "crown", "crush", "curve", "cycle",
        "daily", "dance", "death", "debug", "decay", "dense", "depth", "derby",
        "desk", "devil", "diary", "dirty", "ditch", "dodge", "doubt", "dough",
        "dozen", "draft", "drain", "drama", "drank", "drape", "dream", "dress",
        "dried", "drift", "drill", "drink", "drive", "drone", "drove", "drums",
        "dwarf", "eager", "eagle", "early", "earth", "eight", "elder", "elect",
        "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal", "equip",
        "erode", "error", "essay", "event", "every", "exact", "exile", "exist",
        "extra", "fable", "facet", "faith", "false", "fancy", "fatal", "favor",
        "feast", "fence", "ferry", "fetch", "fever", "fiber", "field", "fifth",
        "fifty", "fight", "final", "first", "fixed", "flame", "flash", "fleet",
        "flesh", "float", "flock", "flood", "floor", "flora", "flour", "fluid",
        "flush", "flute", "focal", "focus", "force", "forge", "forth", "forum",
        "found", "frame", "frank", "fraud", "fresh", "front", "frost", "froze",
        "fruit", "fully", "fungi", "funny", "ghost", "giant", "given", "glass",
        "gleam", "glide", "globe", "gloom", "glory", "gloss", "glove", "grace",
        "grade", "grain", "grand", "grant", "grape", "graph", "grasp", "grass",
        "grave", "great", "green", "greet", "grief", "grill", "grind", "groan",
        "groom", "gross", "group", "grove", "grown", "guard", "guess", "guest",
        "guide", "guild", "guilt", "guise", "gulch", "gully", "heart", "heavy",
        "hedge", "height", "helix", "hello", "hence", "hobby", "honey", "honor",
        "horse", "hotel", "house", "human", "humor", "hurry", "ideal", "image",
        "imply", "index", "indie", "infer", "inner", "input", "irony", "ivory",
        "jewel", "joint", "joker", "judge", "juice", "jumbo", "kebab", "knack",
        "kneel", "knife", "knock", "known", "label", "labor", "large", "laser",
        "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal",
        "lemon", "level", "lever", "light", "limit", "linen", "liner", "lipid",
        "liver", "local", "logic", "loose", "lover", "lower", "loyal", "lucky",
        "lunar", "lunch", "lying", "macro", "magic", "major", "maker", "manor",
        "maple", "march", "marry", "marsh", "match", "mayor", "media", "mercy",
        "merge", "merit", "metal", "meter", "midst", "might", "minor", "minus",
        "mirth", "model", "modem", "money", "month", "moral", "motor", "mount",
        "mouse", "mover", "movie", "music", "naive", "naked", "narrow", "nasal",
        "nasty", "naval", "nerve", "never", "night", "noble", "noise", "north",
        "noted", "novel", "nudge", "nurse", "nylon", "oasis", "occur", "ocean",
        "offer", "often", "olive", "onset", "opera", "orbit", "order", "organ",
        "other", "outer", "oxide", "ozone", "paint", "panel", "panic", "paper",
        "party", "pasta", "paste", "patch", "pause", "peace", "pearl", "pecan",
        "penal", "pence", "penny", "phase", "phone", "photo", "piano", "piece",
        "pilot", "pinch", "pixel", "pizza", "place", "plain", "plane", "plant",
        "plate", "plaza", "plead", "pluck", "plumb", "plume", "plump", "plunge",
        "point", "polar", "pound", "power", "press", "price", "pride", "prime",
        "print", "prior", "prize", "probe", "proof", "prose", "proud", "prove",
        "pulse", "punch", "pupil", "purge", "purse", "queen", "quest", "queue",
        "quick", "quiet", "quite", "quota", "quote", "radar", "radio", "raise",
        "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready",
        "realm", "rebel", "refer", "reign", "relax", "reply", "rider", "ridge",
        "rifle", "right", "rigid", "ruler", "rural", "saint", "salad", "sauce",
        "scale", "scene", "scope", "score", "sense", "serve", "setup", "seven",
        "shade", "shaft", "shake", "shall", "shame", "shape", "share", "shark",
        "sharp", "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine",
        "shirt", "shock", "shore", "short", "shout", "shove", "sight", "sigma",
        "since", "sixth", "sixty", "skate", "skill", "skull", "slash", "slate",
        "sleep", "slice", "slide", "slope", "smart", "smell", "smile", "smoke",
        "snack", "snake", "solid", "solve", "sorry", "sound", "south", "space",
        "spare", "spark", "speak", "speed", "spell", "spend", "spice", "spine",
        "spite", "split", "spoke", "spoon", "spray", "squad", "stack", "staff",
        "stage", "stain", "stair", "stake", "stale", "stall", "stamp", "stand",
        "stark", "start", "state", "steak", "steal", "steam", "steel", "steep",
        "steer", "stern", "stick", "stiff", "still", "stock", "stone", "stood",
        "stool", "store", "storm", "story", "stove", "strap", "straw", "strip",
        "stuck", "study", "stuff", "style", "sugar", "suite", "sunny", "super",
        "surge", "swamp", "swarm", "sweep", "sweet", "swift", "swing", "swirl",
        "sword", "swore", "syrup", "table", "taste", "teach", "theme", "there",
        "thick", "thief", "thing", "think", "third", "thorn", "those", "three",
        "threw", "throw", "thumb", "tiger", "tight", "timer", "tired", "total",
        "touch", "tower", "toxic", "trace", "track", "trade", "trail", "train",
        "trait", "trash", "treat", "trend", "trial", "tribe", "trick", "tried",
        "troop", "truck", "truly", "trunk", "trust", "truth", "tumor", "twice",
        "twist", "ultra", "uncle", "under", "union", "unite", "unity", "until",
        "upper", "upset", "urban", "usage", "usual", "utter", "valid", "value",
        "valve", "vapor", "vault", "venom", "verse", "video", "vigor", "vinyl",
        "viola", "virus", "visit", "vista", "vital", "vivid", "vocal", "vodka",
        "voice", "voter", "wagon", "waist", "waste", "watch", "water", "weave",
        "weigh", "weird", "whale", "wheat", "wheel", "where", "which", "while",
        "whine", "white", "whole", "whose", "wider", "witch", "woman", "world",
        "worry", "worse", "worst", "worth", "would", "wound", "wrath", "write",
        "wrong", "wrote", "yacht", "yield", "young", "youth"
    )

    private val WORDS_6 = listOf(
        "absorb", "accept", "access", "across", "action", "active", "actual",
        "adjust", "advise", "afford", "agenda", "agreed", "almost", "annual",
        "answer", "anyone", "appear", "arcane", "arctic", "assert", "assign",
        "assist", "assume", "assure", "attach", "attain", "attend", "august",
        "author", "avenue", "backup", "bamboo", "banner", "barely", "barrel",
        "basket", "battle", "beauty", "become", "before", "behalf", "behave",
        "behind", "belong", "beside", "beyond", "binary", "bishop", "bitter",
        "blanch", "blazed", "blends", "bless", "blinds", "blocks", "bloody",
        "blossom", "boards", "boiler", "bomber", "border", "borrow", "bottle",
        "bottom", "bounce", "branch", "breach", "breath", "bridge", "bright",
        "broken", "bronze", "bubble", "bucket", "budget", "bullet", "bundle",
        "burden", "bureau", "butter", "button", "camera", "campus", "cancel",
        "carbon", "carpet", "castle", "casual", "catalog", "caught", "center",
        "chance", "change", "charge", "cheese", "choice", "choose", "chosen",
        "church", "circle", "clause", "clean", "clever", "client", "climax",
        "circle", "clinic", "clocks", "closed", "closer", "clouds", "coffee",
        "collar", "colony", "column", "combat", "comedy", "comics", "commit",
        "common", "comply", "convey", "cooker", "cookie", "corner", "costly",
        "cotton", "counts", "couple", "course", "cousin", "covens", "crafty",
        "crashed", "crawls", "create", "credit", "crisis", "cruise", "crystal",
        "custom", "damage", "danger", "daring", "dating", "deadly", "dealer",
        "debris", "decade", "decide", "decker", "defeat", "defend", "define",
        "degree", "demand", "denial", "depart", "depend", "deploy", "depict",
        "derive", "desert", "design", "desire", "detail", "detect", "device",
        "devote", "dictum", "differ", "digest", "dinner", "direct", "dirt",
        "divine", "doctor", "dollar", "domain", "double", "dragon", "drastic",
        "drawer", "driven", "driver", "during", "dynamic", "earned", "easter",
        "editor", "effect", "effort", "eighth", "either", "elects", "element",
        "eleven", "emerge", "empire", "employ", "enable", "encode", "endure",
        "energy", "engage", "engine", "enigma", "enjoys", "enlist", "ensure",
        "entity", "equity", "escape", "estate", "evolve", "exceed", "except",
        "excess", "excuse", "exempt", "expand", "expect", "expert", "export",
        "expose", "extend", "extent", "fabric", "facial", "factor", "fairly",
        "fallen", "family", "famine", "famous", "farmer", "faster", "father",
        "fellow", "female", "finger", "finish", "flower", "flying", "follow",
        "forbid", "forced", "forest", "forget", "formal", "format", "former",
        "fossil", "foster", "fourth", "freely", "freeze", "french", "fridge",
        "friend", "fright", "frozen", "frugal", "future", "galaxy", "garage",
        "garden", "gather", "gender", "gentle", "gifted", "glance", "glands",
        "glazed", "global", "golden", "govern", "grab", "graced", "grades",
        "grainy", "gravel", "guided", "guitar", "hacker", "handle", "happen",
        "harbor", "hardly", "hassle", "hazard", "headed", "health", "heaven",
        "height", "helped", "heroic", "hidden", "highly", "honest", "honors",
        "hoping", "horror", "horses", "hosted", "hostel", "hotels", "hunter",
        "iconic", "ideal", "ignite", "ignore", "impact", "impose", "import",
        "income", "indeed", "indoor", "infant", "inform", "injure", "injury",
        "inputs", "insect", "insert", "inside", "insist", "insure", "intact",
        "intend", "invest", "invite", "island", "itself", "jacket", "jockey",
        "jungle", "junior", "killer", "kindly", "knight", "labels", "ladder",
        "lagoon", "launch", "lawyer", "layout", "leader", "league", "lender",
        "lesser", "lesson", "letter", "likely", "liquid", "listen", "little",
        "lively", "living", "locate", "logged", "lonely", "loosen", "louder",
        "lovely", "luxury", "mainly", "manage", "manner", "marble", "margin",
        "marker", "market", "matter", "medium", "member", "memory", "mental",
        "mentor", "merger", "method", "middle", "midway", "mighty", "mimics",
        "minute", "mirror", "mobile", "modest", "modify", "module", "moment",
        "monkey", "morale", "mortal", "mortar", "mostly", "mother", "motion",
        "murder", "muscle", "museum", "mutant", "mutual", "myself", "namely",
        "narrow", "nation", "native", "nature", "nausea", "nearby", "nearly",
        "nicely", "ninety", "normal", "notice", "notify", "notion", "novice",
        "number", "object", "obtain", "occupy", "offend", "office", "offset",
        "online", "opener", "openly", "oppose", "option", "orange", "origin",
        "outfit", "outlet", "output", "palace", "parent", "parish", "parole",
        "partly", "patrol", "patron", "pencil", "people", "period", "permit",
        "person", "phrase", "pillar", "pirate", "pistol", "planet", "plasma",
        "plates", "plenty", "plight", "plunge", "pocket", "poetry", "poison",
        "police", "policy", "polish", "poorly", "portal", "poster", "potato",
        "powder", "prayer", "prefer", "primal", "primer", "prince", "prison",
        "profit", "proper", "proven", "public", "pulses", "pumpkin", "pursue",
        "puzzle", "racism", "radius", "random", "rarely", "rather", "rating",
        "reader", "realms", "reason", "recall", "recent", "reckon", "record",
        "reduce", "reform", "refuse", "regard", "regime", "region", "reject",
        "relate", "relief", "remain", "remind", "remove", "rental", "repair",
        "repeat", "report", "rescue", "resist", "resort", "result", "retain",
        "retire", "return", "reveal", "review", "revolt", "reward", "rhythm",
        "ridden", "robust", "rocket", "rookie", "rotate", "safari", "safety",
        "salary", "sample", "savage", "saving", "scheme", "school", "screen",
        "script", "search", "season", "second", "secret", "sector", "secure",
        "select", "seller", "senior", "sensor", "series", "settle", "severe",
        "shadow", "shield", "shift", "shiver", "shorts", "should", "showed",
        "signal", "silent", "silver", "simple", "simply", "single", "sister",
        "smooth", "snatch", "social", "sodium", "soften", "solar", "solely",
        "solemn", "sought", "source", "spacer", "sphere", "spirit", "splash",
        "spoken", "sponsor", "spread", "spring", "sprint", "square", "stable",
        "stance", "statue", "status", "steady", "stolen", "strain", "strand",
        "stream", "street", "stress", "strict", "strike", "string", "stroke",
        "strong", "studio", "submit", "subtle", "suburb", "sudden", "suffer",
        "summer", "summit", "supply", "surety", "survey", "switch", "symbol",
        "syndic", "system", "tablet", "tackle", "tactic", "talons", "target",
        "temple", "tenant", "tender", "terror", "thirty", "threat", "thrill",
        "thrive", "throne", "timber", "tissue", "tongue", "toward", "tragic",
        "travel", "tribal", "trophy", "tunnel", "twelve", "twenty", "ulcers",
        "unfair", "unique", "unless", "unlike", "unlock", "update", "upheld",
        "uplift", "upright", "upside", "useful", "utmost", "vacant", "vacuum",
        "valley", "vanish", "vapor", "vastly", "vector", "velvet", "vendor",
        "verify", "versus", "vessel", "veteran", "viable", "vibrant", "viewed",
        "violet", "virtue", "vision", "visual", "volume", "wallet", "wander",
        "warmth", "weapon", "weekly", "weight", "welfare", "western", "whisky",
        "wholly", "window", "winter", "wisdom", "within", "wizard", "wonder",
        "wooden", "worker", "worthy", "yellow"
    )

    private val WORDS_7 = listOf(
        "ability", "absence", "academy", "achieve", "acquire", "address", "advance",
        "adverse", "airport", "alcohol", "already", "analyst", "ancient", "another",
        "anxiety", "anybody", "applied", "arrange", "arsenal", "article", "attempt",
        "attract", "auction", "average", "awesome", "bandage", "banking", "barrier",
        "battery", "bearing", "bedroom", "beloved", "blanket", "bracket", "brother",
        "builder", "burning", "cabinet", "caliber", "calmest", "capable", "capital",
        "caption", "capture", "careful", "carrier", "caution", "ceiling", "central",
        "century", "certain", "chamber", "channel", "chapter", "charity", "charter",
        "chicken", "circuit", "citizen", "classic", "climate", "closing", "cluster",
        "coaster", "collect", "college", "combine", "comfort", "command", "comment",
        "company", "compare", "compete", "complex", "concept", "concern", "conduct",
        "confirm", "connect", "consent", "consult", "contact", "contain", "contest",
        "context", "control", "convert", "correct", "council", "counter", "country",
        "courage", "crucial", "crystal", "culture", "current", "cushion", "customs",
        "cutting", "default", "defense", "deficit", "deliver", "density", "deposit",
        "descent", "deserve", "desktop", "despair", "despite", "destiny", "destroy",
        "develop", "devoted", "diamond", "digital", "discuss", "disease", "display",
        "dispute", "distant", "diverse", "divided", "donated", "dossier", "dramatic",
        "drawing", "dressed", "driving", "dynasty", "eastern", "ecology", "economy",
        "edition", "educate", "elderly", "elected", "elegant", "element", "embrace",
        "emotion", "emperor", "enforce", "engaged", "enhance", "episode", "essence",
        "ethical", "evening", "evident", "examine", "example", "excited", "exclude",
        "execute", "exhaust", "exhibit", "expense", "explain", "explore", "express",
        "extreme", "factual", "failing", "falling", "farming", "fashion", "feature",
        "ferment", "fiction", "fifteen", "fighter", "finance", "finding", "foreign",
        "forever", "formula", "fortune", "forward", "founded", "freedom", "freezer",
        "funding", "funeral", "furnace", "further", "gallery", "gateway", "general",
        "genetic", "genuine", "gesture", "glacier", "glimpse", "glowing", "goddess",
        "grammar", "graphic", "gravity", "greater", "growing", "habitat", "halfway",
        "handful", "handler", "hanging", "happens", "harmful", "harvest", "heading",
        "healing", "healthy", "hearing", "heavily", "helpful", "herself", "highway",
        "himself", "history", "holding", "holiday", "hormone", "horrible", "hostile",
        "housing", "however", "hunting", "husband", "illegal", "illness", "imagine",
        "implant", "implied", "improve", "include", "incomes", "initial", "inject",
        "injured", "inquiry", "install", "instant", "instead", "insulin", "intense",
        "interim", "invalid", "involve", "justice", "justify", "kitchen", "knowing",
        "landing", "lasting", "lateral", "laundry", "leading", "leather", "leaving",
        "lecture", "legally", "lending", "liberal", "liberty", "library", "limited",
        "listing", "literal", "locally", "logical", "lottery", "luggage", "machino",
        "magical", "magnetic", "mailbox", "manager", "mandate", "mansion", "margins",
        "marital", "markers", "massive", "mastery", "meaning", "measure", "medical",
        "meeting", "mention", "message", "million", "mineral", "minimal", "minimum",
        "miracle", "missing", "mission", "mistake", "mixture", "monitor", "monthly",
        "morning", "mounted", "mystery", "natural", "naughty", "nearest", "necktie",
        "needles", "neutral", "notable", "nothing", "nuclear", "nursing", "obvious",
        "offense", "officer", "ongoing", "opening", "operate", "opinion", "organic",
        "outline", "overall", "overlap", "oversee", "painful", "parking", "partial",
        "partner", "passage", "passing", "passion", "patient", "pattern", "payment",
        "penalty", "pending", "percent", "perfect", "perhaps", "persist", "picture",
        "pioneer", "plastic", "playful", "pleased", "popular", "portion", "poverty",
        "predict", "premier", "premium", "prepare", "present", "prevent", "primary",
        "privacy", "private", "problem", "proceed", "process", "produce", "product",
        "profess", "program", "project", "promote", "prosper", "protect", "protein",
        "protest", "provide", "publish", "purpose", "pursuit", "qualify", "quarter",
        "quickly", "radical", "railway", "readily", "reality", "realize", "receipt",
        "receive", "recover", "reduced", "reflect", "refugee", "regular", "related",
        "release", "remains", "removal", "removed", "replace", "request", "require",
        "reserve", "resolve", "respect", "restore", "restrict", "retired", "revenge",
        "reverse", "revival", "routine", "running", "saddest", "sailing", "satisfy",
        "scanner", "scatter", "scholar", "science", "scoring", "scratch", "section",
        "segment", "senator", "service", "session", "setting", "seventh", "several",
        "shelter", "sheriff", "shipment", "shortly", "silence", "sincere", "skilled",
        "slender", "smaller", "smoking", "society", "soldier", "somehow", "speaker",
        "species", "sponsor", "spotted", "squeeze", "stadium", "startup", "stately",
        "station", "storage", "strange", "stretch", "student", "subject", "subsidy",
        "succeed", "surface", "surgery", "surplus", "survive", "suspect", "suspend",
        "sustain", "symbols", "tactics", "tallest", "tangled", "teacher", "teamwork",
        "tension", "therapy", "thought", "through", "tonight", "toolbar", "towards",
        "trained", "transit", "treaty", "trigger", "triumph", "trouble", "trusted",
        "tuesday", "typical", "ugliest", "unified", "uniform", "unknown", "unusual",
        "upgrade", "utility", "vaccine", "valuable", "variety", "vehicle", "venture",
        "version", "veteran", "vibrant", "victims", "village", "vintage", "violent",
        "visible", "vitamin", "volcano", "voltage", "walking", "warranty", "warrior",
        "wealthy", "weather", "website", "wedding", "weekend", "welcome", "welfare",
        "western", "whether", "whisper", "willing", "winning", "without", "witness",
        "working", "writing", "written"
    )

    private val WORDS_8 = listOf(
        "absolute", "abstract", "academic", "accident", "accuracy", "accurate",
        "achieved", "activate", "actually", "addition", "adequate", "adjacent",
        "adjusted", "advanced", "advisory", "advocate", "affected", "aircraft",
        "allocate", "although", "analysis", "announce", "anything", "apparent",
        "appendix", "approach", "approval", "argument", "artistic", "assembly",
        "assigned", "assisted", "athletic", "attached", "attained", "attorney",
        "auction", "audience", "authentic", "backbone", "bankrupt", "baseline",
        "behavior", "bilingual", "billion", "blankets", "blessing", "blindness",
        "bookmark", "bootstrap", "brackets", "branding", "breaking", "briefing",
        "broadband", "building", "bulletin", "business", "calendar", "campaign",
        "capacity", "captured", "careless", "category", "cautious", "ceremony",
        "chairman", "champion", "channels", "checking", "children", "circular",
        "civilian", "classify", "cleaners", "clearing", "climbing", "clipping",
        "clusters", "coaching", "coherent", "collapse", "colleague", "collected",
        "colleges", "colonial", "combatant", "combined", "comedian", "comforted",
        "commander", "commerce", "committed", "commonly", "communal", "compactly",
        "compared", "compiled", "complete", "composed", "compound", "computed",
        "concealed", "conceived", "concerns", "conclude", "concrete", "confined",
        "conflict", "congress", "conquest", "consider", "consists", "constant",
        "consumer", "contains", "contents", "continue", "contract", "contrary",
        "contrast", "convince", "coordinate", "cornered", "corridor", "coverage",
        "creating", "creation", "creative", "criminal", "crippled", "criteria",
        "critical", "crossing", "cultivate", "currency", "customer", "database",
        "deadline", "deafness", "debating", "deceased", "deciding", "decision",
        "decorate", "decrease", "dedicate", "defender", "definite", "demanded",
        "deployed", "describe", "designer", "desolate", "detailed", "detected",
        "deviated", "devotion", "diabetes", "dialogue", "dictator", "digested",
        "dilemma", "diplomat", "disabled", "disaster", "discount", "discover",
        "disorder", "dispatch", "disposal", "dispute", "distance", "distinct",
        "district", "disturb", "documents", "domestic", "dominate", "donation",
        "doubtful", "download", "dramatic", "drawbacks", "dreading", "drinking",
        "dwelling", "dynamics", "earnings", "eastern", "economic", "educated",
        "editions", "educator", "election", "electric", "electron", "elements",
        "emerging", "emission", "emotional", "emphasize", "employee", "employer",
        "empowers", "enclosed", "encoding", "endanger", "enduring", "energies",
        "enforced", "engineer", "enhanced", "ensuring", "entering", "entirely",
        "entrance", "envelope", "equality", "equation", "equipped", "erection",
        "erratic", "escalate", "especial", "essential", "estimate", "evaluate",
        "eventual", "everyone", "evidence", "evolving", "exacting", "examined",
        "example", "excellent", "exchange", "exciting", "excluded", "exclusive",
        "excursion", "excusing", "executed", "exercise", "exhausted", "exhibits",
        "existing", "expanded", "expected", "expedite", "expenses", "experiment",
        "explicit", "exploded", "explored", "exporter", "exposure", "expressed",
        "extended", "external", "extracts", "facility", "factions", "familiar",
        "fanciful", "favorite", "feedback", "festival", "finalist", "findings",
        "finished", "firmness", "flagrant", "fleeting", "flexible", "floating",
        "flooding", "focusing", "follower", "football", "forecast", "foremost",
        "forested", "forever", "formally", "formerly", "fraction", "fragment",
        "freedom", "freezing", "frequent", "friendly", "frontier", "fugitive",
        "function", "furniture", "gathering", "generate", "generous", "gentleman",
        "gigantic", "glaciers", "glancing", "glorious", "governor", "graceful",
        "graduate", "grandeur", "graphics", "grateful", "grouping", "guardian",
        "guidance", "handcuff", "handling", "hands-on", "happened", "happiness",
        "harbored", "hardware", "harmless", "harshness", "harvest", "hazardous",
        "headache", "headline", "healing", "health", "helicopter", "heritage",
        "hesitate", "highland", "highness", "highways", "hijacked", "himself",
        "historic", "homeless", "homework", "honestly", "hopeless", "horrible",
        "hospital", "humanity", "humming", "identical", "identity", "ignition",
        "ignoring", "illusion", "immigrant", "immortal", "imperial", "implicit",
        "implied", "imposed", "improper", "incoming", "increase", "incurred",
        "indicate", "indirect", "industry", "infinity", "informal", "inherent",
        "injuries", "innocent", "insecure", "insiders", "inspects", "inspired",
        "installs", "instance", "intended", "intently", "interact", "interest",
        "interior", "internal", "interval", "intimate", "invasion", "investor",
        "involved", "isolated", "jointly", "journal", "judgment", "judicial",
        "junction", "justices", "justify", "kindness", "labeling", "landmark",
        "language", "laureate", "lawsuits", "lawyers", "layered", "leadered",
        "learning", "leftover", "legalize", "leverage", "liability", "likeness",
        "likewise", "limiting", "linguist", "literacy", "literary", "locating",
        "location", "logistic", "loyalist", "magnetic", "magnific", "majority",
        "mandated", "manifold", "manually", "marching", "marriage", "mastered",
        "matching", "material", "maturity", "maximize", "meaning", "measuring",
        "medalist", "mediator", "medicine", "medieval", "meetings", "membered",
        "membrane", "memorial", "merchant", "messages", "metallic", "midnight",
        "militant", "military", "millions", "mineral", "minimize", "minister",
        "ministry", "minority", "minutes", "mistaken", "moderate", "modified",
        "modular", "molecule", "monetary", "monopoly", "morality", "mortgage",
        "motivate", "mountain", "mourning", "multiply", "mutation", "mutually",
        "mystical", "national", "navigate", "negative", "neglect", "neighbor",
        "nervously", "neutral", "nobility", "nominate", "normally", "northern",
        "notified", "notorious", "nourish", "numerous", "nutrient", "obedient",
        "objective", "observer", "obsolete", "obstacle", "obtained", "occasions",
        "occupied", "offensive", "official", "offshore", "olympics", "omission",
        "oneself", "openness", "operated", "operator", "opponent", "opposite",
        "optimism", "optional", "orbit", "orchestra", "ordering", "ordinary",
        "original", "outbreak", "outcome", "outdoors", "outgoing", "outlined",
        "outlook", "outputs", "overcome", "overload", "oversees", "overview",
        "painting", "paradigm", "paradise", "parallel", "paramour", "partial",
        "particle", "passages", "passenger", "passport", "password", "patience",
        "peaceful", "penalties", "pensions", "perceive", "perfect", "performs",
        "perfumed", "periodic", "personal", "persuade", "petition", "pharmacy",
        "phenomenon", "photography", "physical", "pipeline", "planning", "platform",
        "pleasant", "pleasing", "plumbing", "pneumonia", "poignant", "poisonous",
        "polarize", "policies", "polished", "politely", "politics", "pollution",
        "populate", "portable", "portrait", "position", "positive", "possible",
        "possibly", "postpone", "powerful", "practices", "precedent", "precious",
        "precision", "predict", "preferred", "pregnant", "prejudice", "premises",
        "prepared", "presence", "presents", "preserve", "pressing", "pressure",
        "prestige", "presumed", "pretense", "prevails", "previous", "primarily",
        "printing", "priority", "prisoner", "privacy", "probably", "problems",
        "proceeds", "produced", "producer", "profiles", "profound", "progress",
        "prohibit", "project", "prominent", "promised", "promoted", "promptly",
        "properly", "property", "proposal", "proposed", "prospect", "protected",
        "protocol", "provided", "provider", "province", "prowling", "publicly",
        "purchase", "pursuing", "quadrant", "qualified", "quantity", "quarrels",
        "question", "quickest", "quietest", "radiator", "randomly", "rational",
        "reaction", "readable", "readings", "realized", "rearrange", "reasonable",
        "reassure", "received", "receiver", "recently", "reception", "recharge",
        "rechecks", "reckless", "recognize", "recorded", "recorder", "recovery",
        "recruits", "redefine", "redirect", "redshift", "reflected", "reformer",
        "refugees", "refusing", "regional", "register", "regulate", "rehearse",
        "rejected", "released", "relevant", "reliable", "religion", "relocate",
        "remember", "reminded", "remotely", "rendered", "renewable", "renowned",
        "repeated", "reporter", "republic", "repulsed", "reputed", "required",
        "resident", "resigned", "resisted", "resolved", "resolved", "resource",
        "respond", "restless", "restored", "restrain", "restrict", "retailer",
        "retained", "retiring", "retreat", "retrieve", "reunion", "revealed",
        "revenues", "reversed", "reviewer", "revision", "revival", "revolted",
        "romantic", "rotating", "rounding", "ruin", "rupture", "salaries",
        "sanction", "satellite", "scenario", "schedule", "scheming", "scholar",
        "scientific", "scissors", "scramble", "scrutiny", "seasonal", "secretly",
        "security", "selected", "semester", "sensible", "sensitive", "sentence",
        "separate", "sequence", "sergical", "sessions", "settling", "seventeen",
        "severely", "sexuality", "shelters", "shifting", "shipping", "shortage",
        "shoulder", "showcase", "shutdown", "sidewalk", "sighting", "signaled",
        "silently", "skeleton", "skeptics", "skipping", "slavery", "slippery",
        "smallest", "snapshot", "so-called", "socially", "software", "soldiers",
        "solemnly", "solicit", "solution", "somebody", "somewhat", "souvenir",
        "spacious", "speaking", "specific", "spectrum", "speedway", "sponsors",
        "stability", "stalwart", "standing", "standoff", "standout", "starting",
        "startup", "starving", "stating", "station", "statuary", "steering",
        "stereo", "sterling", "stewards", "stimulus", "stocking", "stopping",
        "storyteller", "straight", "stranded", "strategic", "strength", "strenuous",
        "striking", "stripped", "striving", "stronger", "struggle", "stunning",
        "stupid", "sturdy", "subject", "submarine", "submerged", "submitted",
        "suburban", "succeed", "success", "suffered", "sufficient", "suggest",
        "suitable", "summarize", "sunlight", "superb", "superior", "supplied",
        "supplier", "supposed", "supreme", "surfaced", "surgeon", "surgery",
        "surplus", "surprise", "surrender", "surround", "survival", "survived",
        "survivor", "suspected", "sustained", "swap", "sweeping", "sweetest",
        "swelling", "switching", "symbolic", "symmetry", "syndrome", "synthesis",
        "systemic", "tactical", "tailored", "takeover", "tangled", "targeted",
        "taxation", "teaching", "teamwork", "tendency", "terminal", "terrible",
        "terrific", "territory", "testament", "testimony", "thankful", "thinking",
        "thorough", "thousand", "threaten", "thriller", "thriving", "throne",
        "timetable", "together", "tolerant", "tomorrow", "torture", "touching",
        "tourism", "tournament", "tracking", "traction", "trademark", "tradition",
        "traffic", "tragedy", "training", "transfer", "transit", "transmit",
        "trapped", "trash", "trauma", "traveler", "treasury", "treaties",
        "tremendous", "triathlon", "triggered", "tropical", "troubled", "trusted",
        "trusting", "turbulent", "turnover", "twilight", "ultimate", "umbrella",
        "unable", "unanimous", "uncertain", "uncommon", "underdog", "undergo",
        "underline", "undermine", "underway", "unfairly", "unfolding", "unforeseen",
        "unfriendly", "unhappy", "uniform", "universe", "unknown", "unlikely",
        "unlimited", "unlocked", "unlucky", "unmarked", "unmarried", "unnoticed",
        "unofficial", "unpacked", "unpopular", "unproven", "unreal", "unrelated",
        "unveiled", "unwanted", "unwilling", "upcoming", "updating", "upgraded",
        "uplifting", "uprising", "upturned", "usability", "usefully", "useless",
        "utilized", "utterly", "vacation", "vaccines", "validity", "valuable",
        "vampire", "vanished", "vaporize", "variance", "variants", "various",
        "vascular", "vegetable", "velocity", "vending", "ventures", "verdict",
        "verified", "version", "vertical", "veterans", "vibrant", "vicious",
        "victory", "viewable", "vigorous", "villains", "vintage", "violence",
        "virgin", "virtual", "virtuous", "visible", "visiting", "visually",
        "vitality", "vitamins", "vocalist", "volatile", "volcanic", "volition",
        "voltage", "volumes", "voluntary", "volunteer", "voyage", "vulnerable",
        "wage", "wanderer", "warmness", "warranty", "warriors", "watchful",
        "weakness", "weaponry", "welcome", "welfare", "western", "whatever",
        "wheels", "whenever", "whisper", "whoever", "wildfire", "wildlife",
        "willing", "winning", "wireless", "wisdom", "withdraw", "withhold",
        "within", "without", "witness", "wonderful", "woodland", "woodwork",
        "wordplay", "workflow", "workforce", "workshop", "worsened", "worthless",
        "worthwhile", "wounded", "writing", "written", "wrongful", "younger",
        "yourself", "youthful", "zealous"
    )

    private val COMMON_WORDS: List<String> =
        WORDS_3 + WORDS_4 + WORDS_5 + WORDS_6 + WORDS_7 + WORDS_8

    private val WORDS_BY_LENGTH: Map<Int, List<String>> = run {
        val map = mutableMapOf<Int, MutableList<String>>()
        for (word in COMMON_WORDS) {
            val len = word.length
            if (len < 3 || len > 12) continue
            map.getOrPut(len) { mutableListOf() }.add(word)
        }
        map
    }

    /**
     * Generates a list of words for a given level.
     * Picks `count` words filtered by [minLen]–[maxLen].
     * Has 10% chance of inserting a special word (hyphenated, capitalized, or mixed).
     */
    fun generateWords(
        count: Int,
        minLen: Int,
        maxLen: Int,
        random: Random = Random
    ): List<String> {
        val pool = (minLen..maxLen).flatMap { len ->
            WORDS_BY_LENGTH[len] ?: emptyList()
        }.ifEmpty {
            // Fallback — generate short words
            listOf("the", "and", "for", "are", "but", "not", "you", "all", "can", "had")
        }

        val words = mutableListOf<String>()
        val available = pool.toMutableList()

        repeat(count) {
            // 10% chance: special word
            if (random.nextFloat() < 0.1f && words.size > 1) {
                words.add(generateSpecialWord(minLen, maxLen, random))
            } else {
                if (available.isEmpty()) {
                    available.addAll(pool)
                }
                val idx = random.nextInt(available.size)
                words.add(available.removeAt(idx))
            }
        }

        return words
    }

    private fun generateSpecialWord(minLen: Int, maxLen: Int, random: Random): String {
        return when (random.nextInt(3)) {
            0 -> {
                // Hyphenated: "high-speed"
                val half = ((minLen + maxLen) / 2).coerceAtLeast(3)
                val a = pickWord(half / 2, random)
                val b = pickWord(half / 2, random)
                "$a-$b".take(maxLen).takeIf { it.length >= minLen } ?: "type-strike"
            }
            1 -> {
                // Capitalized: "iPhone"
                val word = pickWord(minLen, random)
                word.replaceFirstChar { it.uppercase() }
            }
            else -> {
                // Mixed alpha-numeric: "7even"
                val word = pickWord(minLen, random)
                if (word.length > 1) {
                    val pos = random.nextInt(word.length)
                    word.substring(0, pos) + random.nextInt(10) + word.substring(pos + 1)
                } else word
            }
        }
    }

    private fun pickWord(targetLen: Int, random: Random): String {
        val list = WORDS_BY_LENGTH[targetLen.coerceIn(3, 12)] ?: listOf("strike")
        return list[random.nextInt(list.size)]
    }

}
